services:
  - type: web
    name: bot-protezione-civile
    runtime: python
    buildCommand: "pip3 install -r requirements.txt"
    startCommand: "python3 main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
